name: Release

# Global defaults - read-only (least privilege)
permissions:
  contents: read
  issues: read
  pull-requests: read

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release  # Requires manual approval in GitHub settings

    # Job-specific write permissions (least privilege)
    permissions:
      contents: write       # Push tags and CHANGELOG
      issues: write        # Create release issues
      pull-requests: write # Create release PRs

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
        with:
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@4d4cb0ab842247caea1963132c242c62aab1e4d5 # v10.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
